-- 시퀀스 명 문법 :: SEQ_테이블명_ID
DROP SEQUENCE SEQ_USER_ID;
CREATE SEQUENCE SEQ_USER_ID start with 1;

DROP SEQUENCE SEQ_MYROOM_ID;
CREATE SEQUENCE SEQ_MYROOM_ID start with 1;

DROP SEQUENCE SEQ_MYROOM_NEXT_ID;
CREATE SEQUENCE SEQ_MYROOM_NEXT_ID start with 1;

DROP SEQUENCE SEQ_MAJOR_ID;
CREATE SEQUENCE SEQ_MAJOR_ID start with 1;

DROP SEQUENCE SEQ_SCHEDULE_ID;
CREATE SEQUENCE SEQ_SCHEDULE_ID start with 1;

DROP SEQUENCE SEQ_GROUP_ID;
CREATE SEQUENCE SEQ_GROUP_ID start with 1;

DROP SEQUENCE SEQ_QNA_ID;
CREATE SEQUENCE SEQ_QNA_ID start with 1;

DROP SEQUENCE SEQ_QNA_COMMENT_ID;
CREATE SEQUENCE SEQ_QNA_COMMENT_ID start with 1;

DROP SEQUENCE SEQ_QNA_RE_ID;
CREATE SEQUENCE SEQ_QNA_RE_ID start with 1;

DROP SEQUENCE SEQ_POLL_ID;
CREATE SEQUENCE SEQ_POLL_ID start with 1;

DROP SEQUENCE SEQ_NOTICE_ID;
CREATE SEQUENCE SEQ_NOTICE_ID start with 1;